import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service',
};

export default function TermsPage() {
  return (
    <div className="legal__content">
      <article className="legal__article">
        <h1>Terms of Service</h1>
        <p className="legal__updated">Last updated: February 2026</p>

        <p>
          Please read these Terms of Service (&ldquo;Terms&rdquo;) carefully before using our AI-powered
          blog generation platform (&ldquo;the Service&rdquo;). By accessing or using the Service, you
          agree to be bound by these Terms.
        </p>

        <div className="legal__callout">
          <h2>AI-Generated Content Disclaimer</h2>
          <p>
            <strong>All blog content produced by this Service is generated entirely by artificial
            intelligence.</strong> This content does not represent the views, opinions, or endorsements
            of the platform, its operators, or any affiliated parties.
          </p>
          <p>
            AI-generated content may contain factual inaccuracies, outdated information, inappropriate
            suggestions, fabricated details, or errors of any kind. The AI models used by this Service
            can and do make mistakes.
          </p>
          <p>
            <strong>You are solely responsible for reviewing, editing, and verifying all AI-generated
            content before publishing, distributing, or using it in any capacity.</strong> Do not publish
            AI-generated content without thorough human review.
          </p>
        </div>

        <h2>Use of the Service</h2>
        <p>
          The Service is a tool designed to assist with creating blog content. It is not a substitute
          for professional writing, editing, or fact-checking. You agree to use the Service in compliance
          with all applicable laws and regulations.
        </p>

        <h2>User Responsibilities</h2>
        <ul>
          <li>
            <strong>Review all output.</strong> You must review and edit all AI-generated content before
            use. You are responsible for ensuring accuracy, appropriateness, and compliance with
            applicable laws.
          </li>
          <li>
            <strong>Brand and trademark compliance.</strong> AI-generated content may reference brand
            names, trademarks, or proprietary terms. You are responsible for ensuring that your use of
            such content complies with trademark laws and brand guidelines.
          </li>
          <li>
            <strong>No harmful use.</strong> You agree not to use the Service to generate content that
            is misleading, defamatory, discriminatory, or otherwise harmful.
          </li>
          <li>
            <strong>Account security.</strong> You are responsible for maintaining the confidentiality
            of your account credentials.
          </li>
        </ul>

        <h2>Intellectual Property</h2>
        <p>
          Content generated by the Service is produced by AI models and may not be eligible for copyright
          protection in all jurisdictions. You are granted a non-exclusive license to use, modify, and
          publish the generated content. The Service does not claim ownership over content you generate.
        </p>
        <p>
          You retain ownership of all inputs you provide (website URLs, brand voice data, instructions,
          and uploaded content).
        </p>

        <h2>No Warranty</h2>
        <p>
          The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties
          of any kind, whether express or implied. We do not warrant that:
        </p>
        <ul>
          <li>AI-generated content will be accurate, complete, or suitable for any purpose</li>
          <li>The Service will be uninterrupted, error-free, or secure</li>
          <li>Results will meet your specific requirements or expectations</li>
          <li>Any defects in the Service will be corrected</li>
        </ul>

        <h2>Limitation of Liability</h2>
        <p>
          To the fullest extent permitted by law, the platform and its operators shall not be liable for
          any indirect, incidental, special, consequential, or punitive damages, including but not limited
          to loss of profits, data, business opportunities, or goodwill, arising from:
        </p>
        <ul>
          <li>Your use of or reliance on AI-generated content</li>
          <li>Errors, inaccuracies, or omissions in generated content</li>
          <li>Any action taken based on AI-generated content</li>
          <li>Unauthorized access to or alteration of your data</li>
          <li>Service interruptions or unavailability</li>
        </ul>

        <h2>Shared Content</h2>
        <p>
          When you create a public share link for a blog post, that content becomes accessible to anyone
          with the link. You are responsible for the content you choose to share publicly. Share links can
          be revoked at any time.
        </p>

        <h2>Termination</h2>
        <p>
          We reserve the right to suspend or terminate your access to the Service at any time, with or
          without cause. Upon termination, your right to use the Service ceases immediately.
        </p>

        <h2>Changes to These Terms</h2>
        <p>
          We may revise these Terms at any time. Continued use of the Service after changes are posted
          constitutes acceptance of the revised Terms.
        </p>

        <h2>Governing Law</h2>
        <p>
          These Terms shall be governed by and construed in accordance with applicable law, without
          regard to conflict of law provisions.
        </p>
      </article>
    </div>
  );
}
